# Generated by Django 3.0.4 on 2020-04-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
    ]
