# Generated by Django 3.0.4 on 2020-04-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_remove_cart_cart_id'),
    ]

    operations = [
    ]
