# Generated by Django 3.0.4 on 2020-03-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='timestamps',
        ),
    ]
