# Generated by Django 3.0.4 on 2020-03-15 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_product_timestamps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='timestamps',
            new_name='timestamp',
        ),
    ]
