# Generated by Django 3.0.4 on 2020-03-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20200315_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='50', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='50', editable=False, null=True),
        ),
    ]
