# Generated by Django 3.0.4 on 2020-03-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20200315_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
