# Generated by Django 3.0.4 on 2020-03-15 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_auto_20200315_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_price',
            new_name='salePrice',
        ),
    ]
