# Generated by Django 3.1.4 on 2021-04-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_remove_product_mainimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='tagLine',
        ),
    ]
