# Generated by Django 3.1.4 on 2021-04-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_auto_20210422_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=10, max_length=2),
        ),
    ]
