# Generated by Django 3.0.4 on 2020-04-12 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20200412_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdefaultaddress',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_default_billing_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userdefaultaddress',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_default_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
