# Generated by Django 3.0.4 on 2020-04-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200412_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='country',
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
