# Generated by Django 3.0.4 on 2020-04-13 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStripeID',
        ),
    ]
