# Generated by Django 3.0.5 on 2020-04-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200412_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='billing',
            field=models.BooleanField(default=True),
        ),
    ]
