# Generated by Django 3.0.4 on 2020-04-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200412_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='taxTotal',
            field=models.DecimalField(decimal_places=4, default=0.0925, max_digits=1000),
        ),
    ]
