# Generated by Django 3.0.4 on 2020-04-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200412_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='taxTotal',
            field=models.DecimalField(decimal_places=2, default=0.09, max_digits=1000),
        ),
    ]
